name: Tests
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: Checks and Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
     
      - name: Run Code Quality Checks
        uses: dagger/dagger-for-github@v8.2.0
        with:
          verb: call
          args: checks
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: "latest"
      
      - name: Run Tests
        uses: dagger/dagger-for-github@v8.2.0
        with:
          verb: call
          args: test
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: "latest"